name: Test Continuous Integration

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/checkout@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
      - run: npm i 
      - run: echo "Pipline works :)"
